export const formItems = [
  {
    label: "CAR CHECK-IN DATE",
    keyName: "CAR_CHECK_IN_DATE",
    inputType: "date",
    isRequired: false,
    className:'text-upper-case',
    validations: {},
  },
  {
    label: "CAR REPAIR DATE",
    keyName: "CAR_REPAIR_DATE",
    inputType: "date",
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "CAR INITIAL",
    keyName: "CAR_INITIAL",
    inputType: "text",
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "CAR NUMBER",
    keyName: "CAR_NUMBER",
    inputType: "number",
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "CHECK UMLER",
    keyName: "CAR_UMLER",
    inputType: "toggle",
    isRequired: false,
    secondary_label: "Yes",
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "CAR KIND",
    keyName: "CAR_KIND",
    inputType: "select",
    isRequired: true,
    validations: {},
    className:'text-upper-case',
    options: [
      {
        label: "SEDAN",
        id: 1,
      },
      {
        label: "COUPE",
        id: 2,
      },
      {
        label: "HATCHBACK",
        id: 3,
      },
    ],
  },
  {
    label: "LOADED",
    keyName: "LOADED",
    inputType: "toggle",
    secondary_label: "Empty",
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "STATUS",
    keyName: "STATUS",
    inputType: "checkbox",
    isRequired: false,
    validations: {},
    className:'text-upper-case',
    checkboxOptions: [
      {
        label: "As Awaiting Shop Space",
        value: "As Awaiting Shop Space",
      },
      {
        label: "As Awaiting Owners Material",
        value: "As Awaiting Owners Material",
      },
      {
        label: "IP - In Paint",
        value: "IP - In Paint",
      },
      {
        label: "REP - Hold  For Repair",
        value: "REP - Hold  For Repair",
      },
    ],
  },
  {
    label: "OWNER",
    keyName: "OWNER",
    inputType: "searchBar",
    isRequired: false,
    validations: {},
    className:'text-upper-case',
    options: [
      {label:"Owner 1", id:1},
      {label:"Owner 2",id:2},
      {label:"Owner 3",id:3},
      {label:"ADMX-ARCHER DANIELS MIDLAND",id:4}
    ],
  },
  {
    label: "SECONDARY OWNER",
    keyName: "SECONDARY_OWNER",
    inputType: "text",
    isRequired: false,
    validations: {},
    className:'text-upper-case',
    options: [],
  },
  {
    label: "BILLING TYPE",
    keyName: "BILLING_TYPE",
    inputType: "select",
    isRequired: true,
    validations: {},
    className:'text-upper-case',
    options: [
      {
        label: "A - AAR",
        id: 1,
      },
      {
        label: "A - BAR",
        id: 2,
      },
    ],
  },
];

export const carsList = [
  {
    car_name: "ABCEF 3456",
    repairs: 10,
    date: "22/10/2021",
    active:false
  },
  {
    car_name: "BCXF 1243",
    repairs: 0,
    date: "20/10/2021",
    active:false
  },
  {
    car_name: "CDMS 6789",
    repairs: 0,
    date: "20/11/2021",
    active:false
  },
];

export const locations = [
  {active:false,name:"QUEST 1"},
 {active:false,name: "QUEST 2"},
 {active:false,name: "QUEST 3"},
 {active:false,name: "QUEST 4"},
 {active:false,name: "QUEST 5"},
 {active:false,name: "QUEST 6"},
 {active:false,name: "QUEST 7"},
 {active:false,name: "QUEST 8"},
 {active:false,name: "QUEST 9"},
{active:false,name:"QUEST 10"},
{active:false,name:"QUEST1 1"},
{active:false,name:"QUEST 12"},
{active:false,name:"QUEST 13"},
];

export const addRepairItems=[
  {
    label: "Validation Type",
    inputType: "select",
    keyName: 'VALIDATION_TYPE',
    isRequired: true,
    validations: {},
    className:'text-capitalize',
    options: [
      {
        label: "SEDAN",
        id: 1,
      },
      {
        label: "COUPE",
        id: 2,
      },
      {
        label: "HATCHBACK",
        id: 3,
      },
    ],
  },{
    label: "User Rules",
    inputType: "toggle",
    keyName: 'USER_RULES',
    secondary_label: "Empty",
    isRequired: false,
    validations: {},
    className:'text-capitalize',
  },{
    label: "Pricing",
    inputType: "select",
    keyName: 'PRICING',
    isRequired: true,
    validations: {},
    className:'text-capitalize',
    options: [
      {
        label: "SEDAN",
        id: 1,
      },
      {
        label: "COUPE",
        id: 2,
      },
      {
        label: "HATCHBACK",
        id: 3,
      },
    ],
  },
  {
    label: "RP",
    inputType: "select",
    keyName: 'RP',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
    options: [
      {
        label: "AUTO",
        id: 1,
      },
      {
        label: "AAR",
        id: 2,
      },
      {
        label: "INTL",
        id: 3,
      },
      {
        label: "User",
        id: 4,
      },
      {
        label: "Pool",
        id: 5,
      },
      {
        label: "None",
        id: 6,
      },
    ],
  },
  {
    label: "AJC",
    inputType: "text",
    keyName: 'AJC',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "LOC",
    inputType: "text",
    keyName: 'LOC',
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "QTY",
    inputType: "text",
    keyName: 'QTY',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "CC",
    inputType: "text",
    keyName: 'CC',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "ACP",
    inputType: "text",
    keyName: 'ACP',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "AQ",
    inputType: "text",
    keyName: 'AQ',
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "AUQ",
    inputType: "text",
    keyName: 'AUQ',
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "WM",
    inputType: "text",
    keyName: 'WM',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "DESCRIPTION",
    inputType: "text",
    keyName: 'DESCRIPTION',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "RJC",
    inputType: "text",
    keyName: 'RJC',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "RCP",
    inputType: "text",
    keyName: 'RCP',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "RQ",
    inputType: "text",
    keyName: 'RQ',
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "RUQ",
    inputType: "text",
    keyName: 'RUQ',
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "RESP",
    inputType: "text",
    keyName: 'RESP',
    isRequired: true,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "CATEOGERY",
    inputType: "text",
    keyName: 'CATEOGERY',
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "INSPECTION",
    inputType: "toggle",
    keyName: 'INSPECTION',
    secondary_label: "Empty",
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  },
  {
    label: "HIDDEN",
    inputType: "toggle",
    keyName: 'HIDDEN',
    secondary_label: "Empty",
    isRequired: false,
    validations: {},
    className:'text-upper-case',
  }

]